events {
  worker_connections 512;
}

http {
  server {
    listen *:44300 ssl;

    # Local development: adicione "127.0.0.1 devopsproject.local" ao /etc/hosts
    # Produção AWS: use o domínio real via CNAME ecommerce.devopsproject.com.br
    server_name devopsproject.local;

    ssl_certificate /etc/nginx/certificates/nginx-certificate.crt;
    ssl_certificate_key /etc/nginx/certificates/signing-request.key;

    location ^~/main/ {
      resolver 127.0.0.11;
      set $upstream_host dpe.main.internal;
      proxy_pass https://$upstream_host;

      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $proxy_protocol_addr;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    }

    location ^~/order/ {
      resolver 127.0.0.11;
      set $upstream_host dpe.order.internal;
      proxy_pass https://$upstream_host;

      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $proxy_protocol_addr;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    }

    location ^~/identity/ {
      resolver 127.0.0.11;
      set $upstream_host dpe.identity.internal;
      proxy_pass https://$upstream_host;

      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $proxy_protocol_addr;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    }

    location ^~/healthchecks/ {
      resolver 127.0.0.11;
      set $upstream_host dpe.health-checker.internal;
      proxy_pass https://$upstream_host;

      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $proxy_protocol_addr;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    }

    location ^~/invoice/ {
      resolver 127.0.0.11;
      set $upstream_host dpe.invoice.internal;
      proxy_pass https://$upstream_host;

      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $proxy_protocol_addr;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    }

    location ^~/notificator/ {
      resolver 127.0.0.11;
      set $upstream_host dpe.notificator.internal;
      proxy_pass https://$upstream_host;

      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $proxy_protocol_addr;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    }

    location / {
      resolver 127.0.0.11;
      set $upstream_host dpe.site.internal;
      proxy_pass http://$upstream_host:3000;

      proxy_set_header Host            $host;
      proxy_set_header X-Real-IP       $proxy_protocol_addr;
      proxy_set_header X-Forwarded-For $proxy_protocol_addr;
    }
  }
}
